/*---------------------------------------IMPORTANT----------------------------------
 * For porting this file to another board make sure that your microcontroller has a UART
 * available and it uses 3.3 Volts otherwise you can damage the transceiver.
 * Replace "Chip_UART_SendBlocking(---)" function with the proper one of your SDK/Platform
 * i.e: HAL_UART_Transmit(...)  if you are using STM32 HAL API.
 */
#include <string.h>
#include "rak811.h"

void config_lora_region(char lora_region[])
{
	//one of the following items:
	//EU868
	//EU433,
	//CN470,
	//IN865,
	//EU868,
	//AU915,
	//US915,
	//KR920,
	//AS923.
	char AT_COMMAND[80]="at+set_config=lora:region:";
	strcat(AT_COMMAND, lora_region);
	strcat(AT_COMMAND, "\r\n");
	Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
}

/*For more details about device classes please refer to the LoRaWAN specification
 * https://lora-alliance.org/resource-hub/lorawanr-specification-v102
 * */
void config_lorawan_class(uint8_t class)
{
	if(class == 0)//Class A
		Chip_UART_SendBlocking(LPC_USART0 , CLASS_A_DEVICE_MESSAGE, strlen(CLASS_A_DEVICE_MESSAGE));

	if(class == 1)//Class B
		Chip_UART_SendBlocking(LPC_USART0 , CLASS_B_DEVICE_MESSAGE, strlen(CLASS_B_DEVICE_MESSAGE));

	if(class == 2)//Class C
		Chip_UART_SendBlocking(LPC_USART0 , CLASS_C_DEVICE_MESSAGE, strlen(CLASS_C_DEVICE_MESSAGE));
}

/*Choose between P2P or LoRaWAN mode*/
void config_lora_work_mode(uint8_t work_mode)
{
	if(work_mode == 0)//LoRaWAN mode
		Chip_UART_SendBlocking(LPC_USART0 , LORAWAN_WORK_MODE, strlen(LORAWAN_WORK_MODE));

	if(work_mode ==1)//LoRa P2P
		Chip_UART_SendBlocking(LPC_USART0 , LORAP2P_WORK_MODE, strlen(LORAP2P_WORK_MODE));
}

/*Choose authentication method
 * OTAA = Over The Air Authentication (RECOMENDED)
 * ABP = Authentication by Personalization
 * */
void config_lora_join_mode(uint8_t join_mode)
{
	if(join_mode == 0)//OTAA
		Chip_UART_SendBlocking(LPC_USART0 , LORAWAN_OTAA_JOIN_MODE, strlen(LORAWAN_OTAA_JOIN_MODE));
	else if(join_mode == 1)//ABP
		Chip_UART_SendBlocking(LPC_USART0 , LORAWAN_ABP_JOIN_MODE, strlen(LORAWAN_ABP_JOIN_MODE));
}

/*Configure device EUI generated by the LoRaWAN network*/
void config_dev_eui(char dev_eui[])
{
	char AT_COMMAND[80]="at+set_config=lora:dev_eui:";
	strcat(AT_COMMAND, dev_eui);
	strcat(AT_COMMAND, "\r\n");
	Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
}

/*Configure application EUI generated by the LoRaWAN network*/
void config_app_eui(char app_eui[])
{
	char AT_COMMAND[80]="at+set_config=lora:app_eui:";
	strcat(AT_COMMAND, app_eui);
	strcat(AT_COMMAND, "\r\n");
	Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
}

/*Configure application key generated by the LoRaWAN network*/
void config_app_key(char app_key[])
{
	char AT_COMMAND[80]="at+set_config=lora:app_key:";
	strcat(AT_COMMAND, app_key);
	strcat(AT_COMMAND, "\r\n");
	Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
}

/*Configure the device to go to sleep after configuring*/
void config_device_sleep(char sleep_command[])
{
	if(!Chip_UART_CheckBusy(LPC_USART0))//Verifies if the UART is Busy
	{
		char AT_COMMAND[80]="at+set_config=device:sleep:";
		strcat(AT_COMMAND, sleep_command);
		strcat(AT_COMMAND, "\r\n");
		Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
	}
}

/*Join the LoRaWAN networkS*/
void lora_join(void)
{
	Chip_UART_SendBlocking(LPC_USART0, LORAWAN_JOIN_COMMAND, strlen(LORAWAN_JOIN_COMMAND));
}

/*Send data using LoRaWAN*/
void lora_send(char payload[40])
{
	if(!Chip_UART_CheckBusy(LPC_USART0))//Verifies if the UART is Busy
	{
		char AT_COMMAND[80] = "at+send=lora:1:";
		strcat(AT_COMMAND, payload);
		strcat(AT_COMMAND, "\r\n");
		Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
	}
}

/*Send data using RAW LORA*/
void lora_send_P2P(char payload[40])
{
	if(!Chip_UART_CheckBusy(LPC_USART0))//Verifies if the UART is Busy
	{
		char AT_COMMAND[80] = "at+send=lorap2p:";
		strcat(AT_COMMAND, payload);
		strcat(AT_COMMAND, "\r\n");
		Chip_UART_SendBlocking(LPC_USART0 , AT_COMMAND, strlen(AT_COMMAND));
	}
}
